### ISSUE TITLE
Conflicting types for int8_t, int16_t and int32_t.

### ISSUE THREAD

**Issue by daniel-starke** [alekmaul/tcc#18]
These types should be declared in `stdint.h` instead of `stddef.h`. However, there is currently also a declaration in `stddef.h` but with implicite signess compared to the explicite signess in `stdint.h`. I suggest to move this all to `stdint.h`.

See:
https://github.com/alekmaul/tcc/blob/756ea8eaaaf734b7ea37d1f15e5f797209ea1e14/stddef.h#L11-L25
and:
https://github.com/alekmaul/tcc/blob/756ea8eaaaf734b7ea37d1f15e5f797209ea1e14/include/stdint.h#L1-L7

**Comment by kobenairb** [comment]
Hi @daniel-starke,

So here you suggest to comment the mentionned lines from  stddef.h and merge them to stdint.h ?

Like something like this in stdint.h:

```
#ifndef _STDINT_H
#define _STDINT_H

#include <stddef.h>

typedef unsigned int uint16_t;
typedef unsigned long long uint32_t;
typedef unsigned char uint8_t;

typedef signed char int8_t;
typedef signed short int16_t;
typedef signed int int32_t;
typedef signed long long int64_t;

#endif

```

And stddef.h:

```
#ifndef _STDDEF_H
#define _STDDEF_H

#define NULL ((void *) 0)
typedef __SIZE_TYPE__ size_t;
typedef __WCHAR_TYPE__ wchar_t;
typedef __PTRDIFF_TYPE__ ptrdiff_t;
#define offsetof(type, field) ((size_t) & ((type *) 0)->field)

#endif
```

My example is based on the develop branch.

**Comment by daniel-starke** [comment]
Yes, something like that. A C99 conform header would define more types of course, but your change would be a good starting point.
See for example https://github.com/kraj/uClibc/blob/master/include/stdint.h

**Comment by kobenairb** [comment]
Ok, I will make this change asap, probably today. About "A C99 conform header would define more types of course", I'm agree with you but TCC is mostly implemented in C90 (See https://github.com/alekmaul/tcc/blob/develop/CodingStyle).

I will also check for your PR, I made some tests and it seems good for me but as spoken together, we need more use cases because our examples are not relevant to test it.

**Comment by daniel-starke** [comment]
> I'm agree with you but TCC is mostly implemented in C90.

Quite normal to use only an old standard to implement a compiler which provides also support for new standards. I do not see any conflict here as we are talking about features provided to the user and not about features needed to build the compiler.

**Comment by kobenairb** [comment]
actually, I completely agree, especially since this library is not used by pvsneslib. I just try to stick as much as possible to tinycc to facilitate updates and diffs. I add the changes you mentioned, I will also add some fixes and improvements. Thanks again for your help.

**Comment by kobenairb** [comment]
I think that we can close this issue due to my last changes from tinycc. 
For use with pvsneslib, the equivalent library is snestypes.h

**Comment by daniel-starke** [comment]
It seems that stdint.h was removed from tcc in the most recent pull request along with other headers.
I cannot find it in `include` anymore.

**Comment by kobenairb** [comment]
Indeed, this file is no longer managed / used with tinycc, so it's kinda deprecated. As this lib is not used by pvsneslib, is it okay for you to close this PR ?

**Comment by daniel-starke** [comment]
So I will need to create a PR against pvsneslib next to include the compatible C standard library headers?

**Comment by kobenairb** [comment]
Not at all, it's already defined in snestypes.h, see here https://github.com/alekmaul/pvsneslib/blob/develop/pvsneslib/include/snes/snestypes.h#L37C1-L50C1
Tell if it's clear for you

**Comment by alekmaul** [comment]
If it's clear, I think we can close this issue

**Comment by daniel-starke** [comment]
Well, this defines custom types, not the C standard ones. I usually stick to the standard than custom ones for code reuse.

**Comment by alekmaul** [comment]
yeah, but as for other devkit, i'm using custom types (u8 is nice for me ;)). 
Do you think it's a problem and does not work fine?
If not , I think we can close the issue.

**Comment by daniel-starke** [comment]
I have no problem if you either clarify somewhere which level of C standard compliance you try to provide or add at least those which are possible.

**Comment by kobenairb** [comment]
tcc is based on the ANSI standard. TCC is mainly implemented in C90. **Do not use any non-C90** functionality that is not already in use. I saw that in the latest version (0.9.27), some implementations of the C99 standard were introduced but I haven't backported those in our version yet. I will update the readme to avoid confusion.

**Comment by kobenairb** [comment]
@daniel-starke can we close this issue ?

**Comment by daniel-starke** [comment]
Yes.
