### ISSUE TITLE
unsupported cpu aarch64

### ISSUE THREAD

**Issue by RetroAntho** [alekmaul/tcc#30]
Hi,
Some month ago, i tried our old version of tcc and did minor changes to have tcc working on arm architecture (i tested on old raspberry pi - 32b) and it was working.

I did the same test today with a raspberry pi 4 64b and tcc does not compile anymore. I do not know if the error is related to the 64b architecture or to the update done to the new version.

I updated the "configure" script to take the new architecture into account :

```
case "$cpu" in
...
aarch64)
    cpu="arm64"
    ;;
...
```
then 
```
...
elif test "$cpu" = "arm64"; then
    echo "ARCH=arm" >>config.mak
    echo "#define HOST_ARM 1" >>$TMPH
...
```

and i finally have this error in libtcc1.c
```
/usr/bin/cc -o lib/libtcc1.o -c lib/libtcc1.c -O2 -Wall
lib/libtcc1.c:135:2: error: #error unsupported CPU type
```

I have some difficulties to understand why and i am comparing with this commit which was working.
https://github.com/alekmaul/tcc/tree/19a8be325cc32b43fcebfbb436820c0b8ad51341

Any clue or information will be appreciated
Thanks in advance

**Comment by kobenairb** [comment]
Hi  @RetroAntho, let me check it. the configure file changed so maybe something is broken. Can you confirm me, if you use the last configure file https://github.com/alekmaul/tcc/tree/19a8be325cc32b43fcebfbb436820c0b8ad51341 with the current tcc version, is it work as expected ? Sorry I never focused on arm arch, so I have to test it.

Edit: It looks to be related to this https://github.com/alekmaul/tcc/blob/9a2d8a931927469d73f8da8e10596444026d925c/tccelf.c#L1313-L1347

**Comment by RetroAntho** [comment]
Hi @kobenairb,

I just tried this commit : https://github.com/alekmaul/tcc/tree/19a8be325cc32b43fcebfbb436820c0b8ad51341

and i got this error :
gcc: error: unrecognized command-line option ‘-m32’
gcc: error: unrecognized command-line option ‘-mpreferred-stack-boundary=4’

I remember i solved it in an other commit but i do not find it anymore. By the way, by updating the condition on arm* (to bypass these options), i confirm that the code compile correctly.

If i remember correctly, i updated the configure script with the last version i found. But maybe by doing it, it will be harder for you to follow the commit history for the upgrade process

**Comment by kobenairb** [comment]
Hi @RetroAntho,

 Can you try to bypass the `#error` macro by doing something like this:
 
 ```c
#ifndef TCC_TARGET_816
#else
#error unsupported CPU
#endif
#endif
```

For the fcc errors, it's related to an old Makefile.

To summarize, can you test the fix above and with the latest version of Makefile ?
-mpreferred-stack-boundary=4 is used to set the stack boundary to a specific alignment. For 32-bit code, 4 means 16 bytes (2^4 = 16). This option may not be valid for the architecture you are building on.

About -m32, if you build on a 32b rasp, your gcc and your libs are in 32b, so I think it is not useful to specify it. Keep me informed ;)

**Comment by RetroAntho** [comment]
Hi @kobenairb,

I do not know what i did yesterday but with the last version of develop branch, it seems that tcc build only by updating the configure script. I pushed the change in develop branch and this part seems to work now.

I think the "strip" function used to check if PVSNESLIB_HOME is defined does not works correctly as i receive this error when launching the "make" command :

```
make[1]: Entering directory '/home/moog/pvsneslib/pvsneslib'
Makefile:2: *** "Please create an environment variable PVSNESLIB_HOME with path to its folder and restart application. (you can do it on windows with <setx PVSNESLIB_HOME "/c/snesdev">)".  Stop.
```

As it is related to the PVSNESLIB repository, i think we can consider this issue solved (i will investigate from pvsneslib side) but i will close it only when i will be able to build all the sample from the lib.

Thanks for your time and explanations

**Comment by RetroAntho** [comment]
Hello,

I did minor changes and now it works correctly, i missed some tests first time :)
The issue is solved!
